### ISSUE TITLE
Add wildcard support for sub-domains

### ISSUE THREAD

**Issue by MartinSchmidt123** [caddy-dns/ionos#3]
Hi,
I am not sure what is possible at the moment, but at least I am quite sure
```
{
    admin off
    skip_install_trust
    acme_ca https://acme-v02.api.letsencrypt.org/directory
    email mail@example.com
    acme_dns ionos {env.YOUR_IONOS_AUTH_API_TOKEN}
}

*.sub.example.com {
    @api host api.sub.example.com
    handle @api {
        reverse_proxy localhost:8000
    }
}
```
is not working.
The domain was changed for this issue report, I used a valid domain and subdomain.

The error is

```json
{
	"level":"error",
	"ts": "<ts>",
	"logger":"tls.issuance.acme.acme_client",
	"msg":"cleaning up solver",
	"identifier":"*.sub.example.com",
	"challenge_type":"dns-01",
	"error":"no memory of presenting a DNS record for sub.example.com (probably OK if presenting failed)"
}

{
	"level":"error",
	"ts": "<ts>",
	"logger":"tls.obtain",
	"msg":"could not get certificate from issuer",
	"identifier":"*.sub.example.com",
	"issuer":"acme-v02.api.letsencrypt.org-directory",
	"error":"[*.sub.example.com] solving challenges: presenting for challenge: adding temporary record for zone sub.example.com.: zone not found (order=https://acme-v02.api.letsencrypt.org/acme/order/<id1>/<id2> (ca=https://acme-v02.api.letsencrypt.org/directory)"
}

{
	"level":"error",
	"ts": "<ts>",
	"logger":"tls.obtain",
	"msg":"will retry","error":"[*.sub.example.com] Obtain: [*.sub.example.com] solving challenges: presenting for challenge: adding temporary record for zone sub.example.com.: zone not found (order=https://acme-v02.api.letsencrypt.org/acme/order/<id1>/<id2>) (ca=https://acme-v02.api.letsencrypt.org/directory)",
	"attempt":1,
	"retrying_in":60,
	"elapsed":1.926568084,
	"max_duration":2592000
}
```

Is it possible to extend this plugin to also support wildcard certs for sub-domains?

In the mean time: do you have any ideas how to workaround this limitation?

Using
```
[..]
*.example.com {
    @api host api.sub.example.com
    handle @api {
        reverse_proxy localhost:8000
    }
}
```
acquire a valid wildcard cert for `*.example.com` but cannot be used for `api.sub.example.com` because caddy does not match sub-sub-domains as documented in https://caddyserver.com/docs/modules/http.matchers.host

**Comment by jandelgado** [comment]
hello @MartinSchmidt123 , 

I did some tests with (built using xcaddy):
```
$ ./caddy version
v2.4.6 h1:HGkGICFGvyrodcqOOclHKfvJC0qTU7vny/7FhYp9hNw=
```
and a configuration like this (DNS name changed to `example.com`):

```
*.sub.example.com {
	tls {
		resolvers 8.8.8.8
		ca https://acme-staging-v02.api.letsencrypt.org/directory
		dns ionos aaaaa.bbbb
	}

    @test host test.sub.example.com 
    handle @test {
        respond "Hello Test"
    }

    @test2 host test2.sub.example.com 
    handle @test2 {
        respond "Hello Test2"
    }
}
```

This works as expected:
* Let's encrypt issues a certificate for `*.sub.<mydomain>.de`
* virtual hosts `test` and `test2` are accessible and presenting the certificate

![image](https://user-images.githubusercontent.com/11670798/163704160-505ba2c3-f275-4f8a-bceb-40a26728609c.png)

So I suspect the problem is not the IONOS DNS module.

**Comment by jandelgado** [comment]
@MartinSchmidt123 any update here from your side, or can we close the issue?

**Comment by MartinSchmidt123** [comment]
Thank you for the testing. 
Adding `resolvers 8.8.8.8` solved my problem. 
I was not aware that the local dns server was beeing used.
We can close this issue.
