### ISSUE TITLE
Register plugin

### ISSUE THREAD

**Issue by lmgarret** [caddy-dns/ionos#6]
Hello, this plugin does not show up when attempting to download it from https://caddyserver.com/download
And when calling 
```
caddy add-package github.com/caddy-dns/ionos
```
I get 
```
Error: download failed: download failed: HTTP 400: github.com/caddy-dns/ionos is not a registered Caddy module package path (id=61cd1130-a55c-4dd8-9734-3cb4fa13bbdf)
```
Seems similar to https://github.com/caddy-dns/googleclouddns/issues/3

**Comment by mholt** [comment]
The plugin maintainer just needs to go to their Account on the Caddy website and claim this package :blush:

**Comment by jandelgado** [comment]
Didn't know the module registry before. But now it's registered. @mholt thanks for the hint

**Comment by mholt** [comment]
Cool :) Thanks! (And no worries, the new site I'm working on should make things a little more clear.)

**Comment by lmgarret** [comment]
Thanks for the quick action!
