### ISSUE TITLE
Keeps ading A records even when "update only"

### ISSUE THREAD

**Issue by Aergernis** [caddy-dns/ionos#7]
Hi,

the DNS is always adding A records to the DNS even when "update only" is set

`	
                dynamic_dns {
		provider ionos <API-KEY>
		domains {
			<DOMAIN>.de *
			<DOMAIN>.de @
		}
		check_interval 300s
		versions ipv4
		update_only
	}`

**Comment by ErikSteiner** [comment]
I would like to extend the ticket and want to report that every update of the IP always generates new A-Records.
To be honest, I'm not sure if that's the intention. Sure, if I set the option “DynDns Update Only”, then of course it shouldn't create any new records, but does it make sense to add new IP addresses for existing records, if the option is unchecked? Not in my opinion, but I'm open to your opinion.

**Comment by jandelgado** [comment]
I think the problem occurs when Caddy is restarted and the IP changed between starts of Caddy. In order to update the A record, this lib uses the identifier (ID field) that is provided by the IONOS API, when the record gets created. As long as Caddy is running and we know the ID, we can update the record using the ID. But once Caddy is restarted, the ID is gone and a new record will be created. I'll have a deeper look on the weekend ...

**Comment by Aergernis** [comment]
If you need some help with testing, i can force a ip change with my setup.

**Comment by Aergernis** [comment]
Just noticed that the records are also added when the Gateway changes in a Multi-WAN setup, even when caddy is not restarting

**Comment by jandelgado** [comment]
Yes, I found a few issues in handling updates and deletes when no ID is provided. I did a major rewrite of the lib. @Aergernis , it would be great if you could test it with your setup. Build a custom caddy version with: 

```
xcaddy build --with github.com/libdns/ionos=github.com/libdns/ionos@search_records_when_id_is_not_provided 
             --with github.com/caddy-dns/ionos
```

That should use my latest development version of libdns-ionos. Let me know if this fixes the problem, thanks.

**Comment by Aergernis** [comment]
since i'm running caddy on my opnsense and i don't kow how to build it from source there, i'll setup e test machine and will try it with it

**Comment by ErikSteiner** [comment]
My problem is, that I use Caddy as a plugin of OPNsense. The plugin uses somehow the upstream version of this Caddy repository. If the changes are related to files, that can also be found on OPNsense, I will build it myself and change the specific files.

**Comment by Aergernis** [comment]
after some fiddling with FreeBSD i got xcaddy to work and could build caddy.

DNS records are now updating correctly when IP changes. Great Job  :heart_eyes:

**Comment by jandelgado** [comment]
Great, thanks for testing. I'll make an official release now
